import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zainr
 */
public class currencyConvert extends javax.swing.JFrame {

    /**
     * Creates new form currencyConvert
     */
    public currencyConvert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Currency = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnterAmount = new javax.swing.JTextField();
        Currency1 = new javax.swing.JComboBox<>();
        Currency2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter amount");

        Currency.setText("Currency 1:");

        jLabel3.setText("Currency 2:");

        EnterAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterAmountActionPerformed(evt);
            }
        });

        Currency1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "YEN", "EURO" }));
        Currency1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Currency1ActionPerformed(evt);
            }
        });

        Currency2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEN", "USD", "EURO" }));
        Currency2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Currency2ActionPerformed(evt);
            }
        });

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(Currency))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Currency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Currency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Currency)
                            .addComponent(Currency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Currency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public class USDYenConversion {
        public void convert(Double value) {
        Double result = value * 134.98;
        messageBox(String.valueOf("YEN" + result), "currencyConvert");
    }
}
/*The provided code includes six classes that represent currency conversion 
operations between different currency types. The classes are as follows:
USDYenConversion: This class performs a currency conversion from US Dollars (USD) to Japanese Yen (YEN).
YenUSDConversion: This class performs a currency conversion from Japanese Yen (YEN) to US Dollars (USD).
YenEuroConversion: This class performs a currency conversion from Japanese Yen (YEN) to Euros (EURO).
EuroYenConversion: This class performs a currency conversion from Euros (EURO) to Japanese Yen (YEN).
USDEuroConversion: This class performs a currency conversion from US Dollars (USD) to Euros (EURO).
EuroUSDConversion: This class performs a currency conversion from Euros (EURO) to US Dollars (USD).
*/
/*Each of these classes contains a method called convert that takes a Double value as input and returns the converted value.
The conversion formula is hard-coded into each class's convert method.
*/
public class YenUSDConversion {
    public void convert(Double value) {
        Double result = value * .0074;
        messageBox(String.valueOf("USD" + result), "currencyConvert");
    }
}

public class YenEuroConversion {
    public void convert(Double value) {
        Double result = value * .0070;
        messageBox(String.valueOf("EURO" + result), "currencyConvert");
    }
}

public class EuroYenConversion {
    public void convert(Double value) {
        Double result = value * 143.66;
        messageBox(String.valueOf("YEN" + result), "currencyConvert");
    }
}

public class USDEuroConversion {
    public void convert(Double value) {
        Double result = value * .94;
        messageBox(String.valueOf("EURO" + result), "currencyConvert");
    }
}

public class EuroUSDConversion {
    public void convert(Double value) {
        Double result = value * 1.06;
        messageBox(String.valueOf("USD" + result), "currencyConvert");
    }
}
/*The jButton1ActionPerformed method calls the appropriate convert method based on the selected currencies and the amount entered by the user. 
It then displays the converted amount in a message box using the messageBox method.*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String currency1 = (String)Currency1.getSelectedItem();
    String currency2 = (String)Currency2.getSelectedItem();
    Double amount = Double.parseDouble(EnterAmount.getText());

    // Perform the appropriate currency conversion based on the selected currencies
    if (currency1.equals("USD") && currency2.equals("YEN")) {
        new USDYenConversion().convert(amount);
    } else if (currency1.equals("YEN") && currency2.equals("USD")) {
        new YenUSDConversion().convert(amount);
    } else if (currency1.equals("YEN") && currency2.equals("EURO")) {
        new YenEuroConversion().convert(amount);
    } else if (currency1.equals("USD") && currency2.equals("EURO")) {
        new USDEuroConversion().convert(amount);
    } else if (currency1.equals("EURO") && currency2.equals("USD")) {
        new EuroUSDConversion().convert(amount);
    } else if (currency1.equals("EURO") && currency2.equals("YEN")) {
        new EuroYenConversion().convert(amount);

}
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void messageBox(String msg,String titleBar)
    {
        JOptionPane.showMessageDialog(null,msg,titleBar,JOptionPane.INFORMATION_MESSAGE);
    }    
    private void EnterAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterAmountActionPerformed

    private void Currency2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Currency2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Currency2ActionPerformed

    private void Currency1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Currency1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Currency1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Currency;
    private javax.swing.JComboBox<String> Currency1;
    private javax.swing.JComboBox<String> Currency2;
    private javax.swing.JTextField EnterAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
